test: Integration tests for v1
liftedinit/many-js pull request #104
Opened 2023-03-31 19:46 UTC by stanleyjones

See #103.

- Can we send an already encoded request and get a response?
- Can we encode a request from bytes and get a response?
- Can we form a request from an object and get a response?
- Can we call a method to form a request and get a response?
- Can we use a shortcut method to form a request and get a response?
- Can we sign a request and get a response (the rest are all anonymous)?

### Test Results

(Currently skipping the KeyValue tests and concentrating on the above.)

```
❯ npm run test:integration

> @liftedinit/many-js@0.1.0-alpha.9 test:integration
> jest --testMatch '**/?(*.)+(integration).[jt]s?(x)'

 PASS  src/__tests__/base-service.integration.ts

Test Suites: 1 skipped, 1 passed, 1 of 2 total
Tests:       3 skipped, 6 passed, 9 total
Snapshots:   0 total
Time:        0.967 s, estimated 1 s
Ran all test suites.
```

2023-04-03 19:21 UTC, fmorency requested changes
You didn't ask for a review, but I'm giving you one anyway! I didn't review the code, as I believe you will need to integrate changes from #103 here.

For the sake of posterity, can you document why you needed to revert https://github.com/liftedinit/many-js/pull/99?

2023-04-03 19:21 UTC, fmorency commented on src/__tests__/data.ts
> +  LEDGER: "http://127.0.0.1:8001",
You should point ports to the ABCI

2023-04-03 21:42 UTC, stanleyjones commented on src/__tests__/data.ts
> +  LEDGER: "http://127.0.0.1:8001",
Done

2023-04-03 21:46 UTC, stanleyjones commented
For the record: The CBOR library we're using assumes Buffers, so replacing them with Uint8Arrays meant that things were getting coded as such in CBOR (and tagged as TypedArrays). There are other CBOR libraries that don't make this assumption (like [cbor-x](https://www.npmjs.com/package/cbor-x)) that we could switch to in the future, but I didn't want to do that at the same time.

2023-04-04 13:23 UTC, fmorency approved these changes
I didn't review the code in-depth. LGTM, assuming comments are addressed. Thanks!

2023-04-04 13:23 UTC, fmorency commented on src/__tests__/data.ts
> +  KEYVALUE: "http://127.0.0.1:8010",
The correct port for kvstore ABCI when running the `run.sh` script is `8011`.

2023-04-04 13:23 UTC, fmorency commented on src/__tests__/keyvalue.integration.ts
> +import { KeyPair, KeyValueService, Request } from "..";
Is this still WIP? Should we remove this from the current PR and write a future kvstore-oriented PR?

2023-04-04 13:23 UTC, fmorency commented on src/message/request/request.ts
> +  // 7: ["nonce", { fn: (value: string) => cbor.encode(value) }],
Remove?

2023-04-04 13:23 UTC, fmorency commented on src/message/request/request.ts
> +      // version: 1,
Remove?

2023-04-04 13:23 UTC, fmorency commented on src/message/request/request.ts
> +      // nonce: makeRandomBytes(16),
Remove?

2023-04-04 15:50 UTC, merged

2023-04-04 15:51 UTC, stanleyjones commented
Acknowledging that there are unaddressed comments here that I'll tackle in the next PR.

- KeyValue port and tests
- Uncomment or remove commented code