feat: Mint and Burn tokens
liftedinit/many-js pull request #106
Opened 2023-05-23 19:23 UTC by stanleyjones

Related:
- liftedinit/roadmap#37
- liftedinit/roadmap#38
- liftedinit/gwen#43

2023-05-23 19:26 UTC, stanleyjones commented on src/network/modules/ledger/ledger.ts
> -  burn: () => Promise<unknown>
`mint` and `burn` are no longer in the `ledger` namespace (for a long time now).

2023-05-23 19:26 UTC, stanleyjones commented on src/network/modules/tokens/__tests__/tokens.test.ts
>      })
Yes, these tests suck.

2023-05-23 19:26 UTC, stanleyjones commented on src/network/modules/tokens/tokens.ts
> +}
Thank you @hansl for making the `@param` for these two methods the same. Much appreciated!

2023-05-23 19:26 UTC, stanleyjones commented on src/network/modules/tokens/types.ts
> +  addresses: TokensAddressMap
ManyJS will let you send multiple addresses and amounts even if Gwen doesn't yet.

2023-05-23 19:42 UTC, fmorency requested changes
Minor thing. Thanks @stanleyjones!

2023-05-23 22:00 UTC, stanleyjones commented on src/network/modules/tokens/tokens.ts
> +}
Thanks!

2023-05-25 16:02 UTC, hansl approved these changes

2023-05-25 18:21 UTC, merged